from tkinter import *
root = Tk()
style.configure("TButton", padding=6, relief="flat", background="#ccc")

one = Button(root, text = '1')
two = Button(root, text = '2')
tre = Button(root, text = '3')
fou = Button(root, text = '4')
fiv = Button(root, text = '5')
six = Button(root, text = '6')
sev = Button(root, text = '7')
osm = Button(root, text = '8')
nin = Button(root, text = '9')
zro = Button(root, text = '0')
sum = Button(root, text = '+')
subtraction = Button(root, text = '- ')
multiplication = Button(root, text = 'x ')
division = Button(root, text = '/ ')
equaly = Button(root, text = '=')
fractional = Button(root, text = '. ')
squaring = Button(root, text = '^')
sq_root = Button(root, text = '√')
tru = Button(root, text = '±')
clean = Button(root, text = 'C', bg="orange", fg="white")

one.grid(row = 2, column = 1)
two.grid(row = 2, column = 2)
tre.grid(row = 2, column = 3)
fou.grid(row = 3, column = 1)
fiv.grid(row = 3, column = 2)
six.grid(row = 3, column = 3)
sev.grid(row = 4, column = 1)
osm.grid(row = 4, column = 2)
nin.grid(row = 4, column = 3)
zro.grid(row = 5, column = 2)
sum.grid(row = 4, column = 4)
subtraction.grid(row = 3, column = 4)
multiplication.grid(row = 2, column = 4)
division.grid(row = 1, column = 4)
equaly.grid(row = 5, column = 4)
fractional.grid(row = 5, column = 3)
squaring.grid(row = 1, column = 3)
sq_root.grid(row = 1, column = 2)
tru.grid(row = 5, column = 1)
clean.grid(row = 1, column = 1)

root.geometry('200x150+300+200')
root.resizable(True, False)

root.mainloop()